apiVersion: v1
kind: Secret
metadata:
  name: dockersecrets
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXdHphR0Y1ZEhjNlFXdHJhVEl5UUdOdmIyd2giCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
