apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: to-do-app-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80